[extend]
useDefault = true

[allowlist]
paths = [
  '''_test\.go$''',
  '''examples/.*\.tf$''',
  '''examples/.*\.tfvars\.example$''',
  '''examples/scenarios/.*/test-deploy-key$''',
  '''docs/guides/.*\.md$''',
  '''templates/guides/.*\.md\.tmpl$''',
]
