package names

const (
	AttrUUID            = "uuid"
	AttrName            = "name"
	AttrDescription     = "description"
	AttrProjectUUID     = "project_uuid"
	AttrServerUUID      = "server_uuid"
	AttrEnvironmentName = "environment_name"
	AttrImage           = "image"
	AttrIsPublic        = "is_public"
	AttrPublicPort      = "public_port"
	AttrStatus          = "status"
	AttrFQDN            = "fqdn"
	AttrPortsExposes    = "ports_exposes"
	AttrBuildPack       = "build_pack"
	AttrGitRepository   = "git_repository"
	AttrGitBranch       = "git_branch"
	AttrDockerImage     = "docker_image"
	AttrKey             = "key"
	AttrValue           = "value"
	AttrType            = "type"
	AttrEnabled         = "enabled"
	AttrFrequency       = "frequency"
	AttrEndpoint        = "endpoint"
	AttrBucket          = "bucket"
	AttrRegion          = "region"
	AttrAccessKey       = "access_key"
	AttrSecretKey       = "secret_key"
	AttrPrivateKey      = "private_key"
	AttrPrivateKeyUUID  = "private_key_uuid"
	AttrIP              = "ip"
	AttrPort            = "port"
	AttrUser            = "user"
)